### ISSUE TITLE
[Developers] Restructure dev doc: basics

### ISSUE THREAD

**Issue by ipapandinas** [capsule-corp-ternoa/ternoa-doc#117]
## Todo

- [x] Introduction: Ternoa building tools + glossary
- [x] Get started
  - [x] Prerequisites: wallet with alpha CAPS
  - [x] Installation: ternoa-js library
  - [x] Mint NFT
  - [x] View NFT
  - [x] Sold NFT
... structure by features with no separation between Indexer & SDK
