### ISSUE TITLE
[Developers] Indexer

### ISSUE THREAD

**Issue by ipapandinas** [capsule-corp-ternoa/ternoa-doc#33]
### Description

This section is Indexer focused and will contain several subsections to understand how Indexer works.
We need to explain in details the difference with the Dictionary and how to use the Dictionary in pair with the Indexer to improve syncing performances.
Installation material guides is also super important, we have to explain a to run our own Indexer locally.

### Todo

- [x] Introduction: vision + subquery + architecture design choices
- [x] Getting started + Contribution
- [x] Queries
- [x] Installation guidelines: node + docker + postgres usage
- [ ] Tutorial: create an new Entity
- [ ] References
   - Community references
   - Github Discussions
